Import('RTT_ROOT')
Import('rtconfig')
from building import *

cwd = GetCurrentDir()
src	= Glob('*.c')
CPPPATH = [cwd]

group = DefineGroup('RTC', src, depend = ['USING_STM32_RTC'], CPPPATH = CPPPATH)

Return('group')
