Import('RTT_ROOT')
Import('rtconfig')
from building import *

cwd = GetCurrentDir()
src	= Glob('src/*.c')
#src = src + ['src/halSpi.c' + 'src/CC1101.c']
#src += ['src/CC1101.c']

path = [cwd + '/inc']

group = DefineGroup('Rf', src, depend = [''], CPPPATH = path)

Return('group')
