Import('RTT_ROOT')
Import('rtconfig')
from building import *

cwd = GetCurrentDir()
src	= Glob('*.c')
CPPPATH = [cwd]

group = DefineGroup('LCD', src, depend = ['RT_USING_RTGUI'], CPPPATH = CPPPATH)

Return('group')
